name: autocycler
channels:
  - conda-forge
  - bioconda
dependencies:
  - autocycler>=0.5.0
  - canu>=2.3
  - flye>=2.9.6
#  - lja>=0.2
  - metamdbg>=1.0
  - miniasm>=0.3
  - minimap2>=2.28
  - minipolish>=0.2.0
  - myloasm>=0.1.0
  - necat>=0.0.1_update20200803
  - nextdenovo>=2.5.2
  - nextpolish>=1.4.1
  - plassembler>=1.8.0
  - racon>=1.5.0
  - raven-assembler>=1.8.3
  - wtdbg>=2.5
  - parallel
